### ISSUE TITLE
Idee: mehrere presets mit einem Befehl

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedSetBlock#1]
Ist es möglich in RedCommandSystem die Funktion hinzuzufügen, auch mehrere presets einer Gruppe mit einem Befehl auszuführen?

**Beispiel:**

`/redblockedit -p items-kill items-spawn_signalstaerke-2`

"items-kill" und "items-spawn_signalstaerke-2" währen jetzt 2 presets innerhalb der Gruppe "redblockedit".

```
redblockedit:
  syntax: "<position> <preset>"
  aliases:
  - rbe
  permission: rwm.blockedit
  wrong-world:
    commands: []
    output: false
    permissions: []
    run-as-op: true
    run-as-console: false
  execute:
    commands:
    - '%preset%'
    output: false
    permissions: []
    run-as-op: true
    run-as-console: false
  presetpermissions: false
  presets:
    items-kill: '...'
    items-spawn_signalstaerke-2: '...'
```

**Hintergrund / Idee:**

Somit könnte ich einen Selbstaufruf via Chat-Interaktion realisieren, um per Chat die Signalstärke zu editieren:

`Chatmenu_A: 'tellraw %player% ["",{"text":"    "},{"text":"... [2] ...","clickEvent":{"action":"run_command","value":"redblockedit -p items-kill items-spawn_signalstaerke-2"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"2 Items"}]}}}'`

Die Run_Command Funktion von MC lässt ja nur zu, ein Befehl auszuführen - somit währe das eine sinvolle Art die Commands zu serialisieren.

Ich habe damals schon eine ähnliche Variante entwickelt, die die Befehle serialisierte - das war aber eher nur tricky und keine Dauerlösung.
